services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
    env_file:
      - .env
    command: sh -c "npx drizzle-kit push && npx tsx main.ts"
    networks:
      - app-net

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abc123!@#
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-net

volumes:
  postgres_data:

networks:
  app-net:
    external: true
